### ISSUE TITLE
 ios 配置Key  是写在appdelegate里面么 具体是写在哪里

### ISSUE THREAD

**Issue by JasonStu** [GKerison/react-native-ushare#2]
[UShareHelper configLog:BOOL];
[UShareHelper configUShare:UMENG_KEY];
[UShareHelper configQQ:appID];
[UShareHelper configWeiXin:appKey appSecret:appSecret];
[UShareHelper configSina:appKey appSecret:appSecret];

**Comment by GKerison** [comment]
最好是，确保使用前初始化就行

**Comment by America-first-melon** [comment]
复制到 appdelegate.m  直接红色叹号啊

**Comment by GKerison** [comment]
@America-first-melon 
库复制进去之后，相应的值肯定要根据自己的项目做修改。
